# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(975, 388)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(170, 100, 631, 221))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(110, 30, 81, 20))
        self.label_2.setObjectName("label_2")
        self.name = QtWidgets.QLineEdit(parent=self.groupBox)
        self.name.setGeometry(QtCore.QRect(220, 20, 231, 31))
        self.name.setObjectName("name")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(110, 100, 81, 20))
        self.label_3.setObjectName("label_3")
        self.passw = QtWidgets.QLineEdit(parent=self.groupBox)
        self.passw.setGeometry(QtCore.QRect(220, 90, 231, 31))
        self.passw.setObjectName("passw")
        self.btnlogin = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnlogin.setGeometry(QtCore.QRect(280, 140, 93, 28))
        self.btnlogin.setObjectName("btnlogin")
        self.btnregister = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnregister.setGeometry(QtCore.QRect(280, 180, 93, 28))
        self.btnregister.setObjectName("btnregister")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(220, -40, 631, 171))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "ĐĂNG NHẬP"))
        self.label_2.setText(_translate("Dialog", "TÀI KHOẢN:"))
        self.label_3.setText(_translate("Dialog", "MẬT KHẨU:"))
        self.btnlogin.setText(_translate("Dialog", "ĐĂNG NHẬP"))
        self.btnregister.setText(_translate("Dialog", "ĐĂNG KÝ"))
        self.label.setText(_translate("Dialog", "        PHẦN MỀM QUẢN LÝ BÁN NÔNG SẢN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
