# Form implementation generated from reading ui file 'users.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_UserManagement(object):
    def setupUi(self, UserManagement):
        UserManagement.setObjectName("UserManagement")
        UserManagement.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=UserManagement)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableUsers = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableUsers.setObjectName("tableUsers")
        self.tableUsers.setColumnCount(0)
        self.tableUsers.setRowCount(0)
        self.verticalLayout.addWidget(self.tableUsers)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblUserID = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblUserID.setObjectName("lblUserID")
        self.gridLayout.addWidget(self.lblUserID, 0, 0, 1, 1)
        self.txtUserID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtUserID.setObjectName("txtUserID")
        self.gridLayout.addWidget(self.txtUserID, 0, 1, 1, 1)
        self.lblUsername = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblUsername.setObjectName("lblUsername")
        self.gridLayout.addWidget(self.lblUsername, 1, 0, 1, 1)
        self.txtUsername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtUsername.setObjectName("txtUsername")
        self.gridLayout.addWidget(self.txtUsername, 1, 1, 1, 1)
        self.lblEmail = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblEmail.setObjectName("lblEmail")
        self.gridLayout.addWidget(self.lblEmail, 2, 0, 1, 1)
        self.txtEmail = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtEmail.setObjectName("txtEmail")
        self.gridLayout.addWidget(self.txtEmail, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btnAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAdd.setObjectName("btnAdd")
        self.buttonLayout.addWidget(self.btnAdd)
        self.btnEdit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEdit.setObjectName("btnEdit")
        self.buttonLayout.addWidget(self.btnEdit)
        self.btnDelete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDelete.setObjectName("btnDelete")
        self.buttonLayout.addWidget(self.btnDelete)
        self.btnExportExcel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExportExcel.setObjectName("btnExportExcel")
        self.buttonLayout.addWidget(self.btnExportExcel)
        self.verticalLayout.addLayout(self.buttonLayout)
        UserManagement.setCentralWidget(self.centralwidget)

        self.retranslateUi(UserManagement)

    def retranslateUi(self, UserManagement):
        _translate = QtCore.QCoreApplication.translate
        UserManagement.setWindowTitle(_translate("UserManagement", "Quản lý người dùng"))
        self.lblUserID.setText(_translate("UserManagement", "Mã người dùng:"))
        self.lblUsername.setText(_translate("UserManagement", "Tên đăng nhập:"))
        self.lblEmail.setText(_translate("UserManagement", "Email:"))
        self.btnAdd.setText(_translate("UserManagement", "Thêm"))
        self.btnEdit.setText(_translate("UserManagement", "Sửa"))
        self.btnDelete.setText(_translate("UserManagement", "Xóa"))
        self.btnExportExcel.setText(_translate("UserManagement", "Xuất Excel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UserManagement = QtWidgets.QMainWindow()
    ui = Ui_UserManagement()
    ui.setupUi(UserManagement)
    UserManagement.show()
    sys.exit(app.exec())
